apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: cat-toml
  namespace: bots
spec:
  inputs:
    resources:
      - name: source
        type: git

  steps:
    - name: cat
      image: ubuntu
      command: ["/bin/bash", "-c"]
      args:
        - "cat /workspace/source/Gopkg.toml"
