apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: dep-update
  namespace: bots
spec:
  inputs:
    params:
    - name: ORGANIZATION
    - name: REPOSITORY
    - name: DEPENDENCIES
    - name: BRANCH
      default: master
    - name: ASSIGNEE
      default: mattmoor
    resources:
    - name: source
      type: git

  steps:

  - name: tomles
    image: ko://github.com/n3wscott/chatbot/cmd/tomles
    args:
    - "update"
    - "github.com/cloudevents/sdk-go"
    - "--revision=3673e23532dccb38196f600eec7e8b7090ecfb12"
    - "--filename=/workspace/source/Gopkg.toml"
    - "--verbose"

  - name: dep
    image: gcr.io/snichols-vmw/dep:latest
    command: ["/bin/bash", "-c"]
    resources:
      requests:
        cpu: 3000m
        memory: 2Gi
    args:
    - |
      set -e
      set -x
      export PARENT_DIR=${GOPATH}/src/github.com/$(inputs.params.ORGANIZATION)
      if [ "$(inputs.params.ORGANIZATION)" == "knative" ]
      then
        export PARENT_DIR=${GOPATH}/src/knative.dev
      fi
      mkdir -p ${PARENT_DIR}
      ln -s /workspace/source ${PARENT_DIR}/$(inputs.params.REPOSITORY)
      cd ${PARENT_DIR}/$(inputs.params.REPOSITORY)
      export REPO_ROOT_DIR=${PARENT_DIR}/$(inputs.params.REPOSITORY)
      go get -u github.com/google/licenseclassifier
      go get -u github.com/knative/test-infra/tools/dep-collector
      export PATH=${PATH}:${GOPATH}/bin
      dep ensure -update $(inputs.params.DEPENDENCIES)
      # Sometimes we "fix up" ./vendor, so run this for good measure.
      ./hack/update-deps.sh
      # We may pull in code-generator updates.
      #./hack/update-codegen.sh
    env:
    - name: GOPATH
      value: /tmp/go

  - name: prbuilder
    image: ko://github.com/n3wscott/chatbot/cmd/prbuilder
    args:
    - "--workspace=/workspace/source"
    - "--repo=$(inputs.params.ORGANIZATION)/$(inputs.params.REPOSITORY)"
    - "--target=$(inputs.params.BRANCH)"
    - "--commit-branch=random"
    - "--title=Auto-update dependencies"
    - "--body"
    - |
        Produced via:
          `dep ensure -update $(inputs.params.DEPENDENCIES)`
        /assign $(inputs.params.ASSIGNEE)
        /cc $(inputs.params.ASSIGNEE)

    # This mimics the runtime contract of the GithubBinding
    volumeMounts:
    - name: github-binding
      mountPath: /var/bindings/github

  volumes:
  - name: github-binding
    secret:
      secretName: github-bots
