apiVersion: gateway.n3wscott.com/v1alpha1
kind: GitHub
metadata:
  name: knative
spec:
  org: knative
  repos:
    - pkg
    - eventing
    - eventing-contrib
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1alpha1
      kind: Broker
      name: default