apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  generateName: dep-builder-
  namespace: bots
spec:
  taskRef:
    # kubectl apply -f https://raw.githubusercontent.com/tektoncd/catalog/master/kaniko/kaniko.yaml
    name: kaniko
  inputs:
    resources:
    - name: source
      resourceSpec:
        type: git
        params:
        - name: url
          value: https://github.com/mattmoor/dep.git
  outputs:
    resources:
    - name: image
      resourceSpec:
        type: image
        params:
        - name: url
          value: gcr.io/snichols-vmw/dep:latest