apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  generateName: test-tomles-
  namespace: bots
spec:
  taskRef:
    name: tomles
  inputs:
    resources:
    - name: source
      resourceSpec:
        type: git
        params:
        - name: url
          value: https://github.com/botless/commands.git
    params:
    - name: DEPENDENCY
      value: github.com/cloudevents/sdk-go
    - name: VERSION
      value: v1.0.0