apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  generateName: test-cat-toml-
  namespace: bots
spec:
  taskRef:
    name: cat-toml
  inputs:
    resources:
    - name: source
      resourceSpec:
        type: git
        params:
        - name: url
          value: https://github.com/botless/commands.git
