

apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  generateName: run-toml-pipe-
  namespace: bots
spec:
  pipelineRef:
    name: toml-pipe
  resources:
    - name: source-git
      resourceSpec:
        type: git
        params:
          - name: url
            value: https://github.com/botless/commands.git
  params:
    - name: GOPKG
      value: github.com/botless/commands
    - name: ORGANIZATION
      value: botless
    - name: REPOSITORY
      value: commands
    - name: DEPENDENCY
      value: github.com/cloudevents/sdk-go
    - name: VERSION
      value: v1.0.0
