
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: toml-pipe
  namespace: bots
spec:
  resources:
    - name: source-git
      type: git
  params:
    - name: GOPKG
    - name: DEPENDENCY
    - name: ORGANIZATION
    - name: REPOSITORY
    - name: REVISION
      default: ""
    - name: BRANCH
      default: ""
    - name: VERSION
      default: ""

  tasks:
    - name: cat-pre
      taskRef:
        name: cat-toml
      resources:
        inputs:
          - name: source
            resource: source-git

    - name: tomles
      taskRef:
        name: tomles
      resources:
        inputs:
          - name: source
            resource: source-git
        outputs:
          - name: source
            resource: source-git
      params:
        - name: DEPENDENCY
          value: "$(params.DEPENDENCY)"
        - name: REVISION
          value: "$(params.REVISION)"
        - name: BRANCH
          value: "$(params.BRANCH)"
        - name: VERSION
          value: "$(params.VERSION)"

    - name: update-deps
      taskRef:
        name: update-deps
      resources:
        inputs:
          - name: source
            resource: source-git
            from: [tomles]
        outputs:
          - name: source
            resource: source-git
      params:
        - name: GOPKG
          value: "$(params.GOPKG)"
        - name: DEPENDENCIES
          value: "$(params.DEPENDENCY)"

    - name: cat-post
      taskRef:
        name: cat-toml
      resources:
        inputs:
          - name: source
            resource: source-git
            from: [update-deps]

# TODO: conditional on if changes.
    - name: pullrequest
      taskRef:
        name: pullrequest
      resources:
        inputs:
          - name: source
            resource: source-git
            from: [update-deps]
      params:
        - name: REPOSITORY
          value: "$(params.REPOSITORY)"
        - name: ORGANIZATION
          value: "$(params.ORGANIZATION)"
        - name: BRANCH
          value: "$(params.BRANCH)"
        - name: DEPENDENCIES
          value: "$(params.DEPENDENCY)"
